-- =============================================
-- Question & Answer Seed Data
-- 4 types × 35 snakes = 140 questions
-- Run: sqlite3 data/data.db < seed_questions.sql
-- =============================================

PRAGMA foreign_keys = ON;

-- ── identify_by_image (35 questions) ────────────────
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (1, 1, 'identify_by_image', 'What species of snake is shown in this image?', 1, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (1, 'Common Cat Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (2, 2, 'identify_by_image', 'Identify the snake in the image.', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (2, 'Ceylon Krait', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (3, 3, 'identify_by_image', 'What snake is depicted in this photograph?', 1, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (3, 'Spectacled Cobra', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (4, 4, 'identify_by_image', 'Can you identify this snake from the image?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (4, 'Green Vine Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (5, 5, 'identify_by_image', 'Name the snake shown in this image.', 1, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (5, 'Russell''s Viper', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (6, 6, 'identify_by_image', 'What snake is shown here?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (6, 'Ceylon Trinket Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (7, 7, 'identify_by_image', 'Identify this snake from its photograph.', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (7, 'Common Sand Boa', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (8, 8, 'identify_by_image', 'What species is this snake?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (8, 'Starred Bronzeback', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (9, 9, 'identify_by_image', 'What snake is pictured here?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (9, 'Common Wolf Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (10, 10, 'identify_by_image', 'Identify the snake in this image.', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (10, 'Hump-nosed Pit Viper', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (11, 11, 'identify_by_image', 'What snake is shown in this image?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (11, 'Sri Lanka Green Pit Viper', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (12, 12, 'identify_by_image', 'Name this snake from the image provided.', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (12, 'Checkered Keelback', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (13, 13, 'identify_by_image', 'What large snake is shown in this photograph?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (13, 'Indian Python', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (14, 14, 'identify_by_image', 'Identify this snake from its image.', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (14, 'Sri Lanka Pipe Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (15, 15, 'identify_by_image', 'What snake is depicted here?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (15, 'Banded Racer', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (16, 16, 'identify_by_image', 'Identify the cobra shown in this image.', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (16, 'Indian Cobra', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (17, 17, 'identify_by_image', 'What pit viper is shown in this photograph?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (17, 'Ceylon Fer-de-Lance', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (18, 18, 'identify_by_image', 'Identify this large snake from the image.', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (18, 'Oriental Rat Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (19, 19, 'identify_by_image', 'What snake is shown gliding in this image?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (19, 'Sri Lanka Flying Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (20, 20, 'identify_by_image', 'Identify the krait in this photograph.', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (20, 'Common Krait', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (21, 21, 'identify_by_image', 'What secretive snake is shown in this image?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (21, 'Slender Coral Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (22, 22, 'identify_by_image', 'Identify this arboreal viper from the image.', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (22, 'Large-scaled Pit Viper', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (23, 23, 'identify_by_image', 'What tiny snake is shown in this photograph?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (23, 'Sri Lanka Worm Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (24, 24, 'identify_by_image', 'Identify this tree snake from the image.', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (24, 'Painted Bronzeback', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (25, 25, 'identify_by_image', 'What semi-aquatic snake is shown here?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (25, 'Olive Keelback', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (26, 26, 'identify_by_image', 'Identify this rare snake from the image.', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (26, 'Indian Egg-Eating Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (27, 27, 'identify_by_image', 'What snake is pictured in this image?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (27, 'Sri Lanka Kukri Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (28, 28, 'identify_by_image', 'Identify this large python from the photograph.', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (28, 'Reticulated Python', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (29, 29, 'identify_by_image', 'What cat snake is shown in this image?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (29, 'Forsten''s Cat Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (30, 30, 'identify_by_image', 'Identify this burrowing snake from the image.', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (30, 'Sri Lanka Shieldtail', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (31, 31, 'identify_by_image', 'What keelback snake is shown here?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (31, 'Buff-striped Keelback', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (32, 32, 'identify_by_image', 'Identify this vine snake from the photograph.', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (32, 'Ceylon Coachwhip', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (33, 33, 'identify_by_image', 'What arboreal boa is shown in this image?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (33, 'Sri Lanka Tree Boa', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (34, 34, 'identify_by_image', 'Identify this smooth-scaled snake from the image.', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (34, 'Common Smooth Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (35, 35, 'identify_by_image', 'What palm viper is shown in this photograph?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (35, 'Sri Lanka Palm Viper', 1);

-- ── identify_by_description (35 questions) ──────────
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (36, 1, 'identify_by_description', 'A mildly venomous, non-aggressive snake found in trees and shrubs at night. What snake is this?', 1, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (36, 'Common Cat Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (37, 2, 'identify_by_description', 'A highly venomous nocturnal krait endemic to Sri Lanka whose bites often occur while victims sleep. What snake is this?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (37, 'Ceylon Krait', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (38, 3, 'identify_by_description', 'An iconic hooded snake that spreads its hood when threatened and is a leading cause of fatalities in Sri Lanka. What snake is this?', 1, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (38, 'Spectacled Cobra', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (39, 4, 'identify_by_description', 'A slender bright-green snake with a sharply pointed snout that is a master of camouflage in foliage. What snake is this?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (39, 'Green Vine Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (40, 5, 'identify_by_description', "A heavy-bodied snake with a distinctive chain pattern that is one of Sri Lanka's most dangerous. What snake is this?", 1, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (40, 'Russell''s Viper', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (41, 6, 'identify_by_description', 'A large nocturnal constrictor often found near human settlements hunting rodents. What snake is this?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (41, 'Ceylon Trinket Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (42, 7, 'identify_by_description', 'A stout burrowing snake with a short blunt tail living in dry sandy areas. What snake is this?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (42, 'Common Sand Boa', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (43, 8, 'identify_by_description', 'A slender fast-moving daytime snake with iridescent bronze scales commonly seen in gardens. What snake is this?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (43, 'Starred Bronzeback', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (44, 9, 'identify_by_description', 'A small nocturnal snake often found inside homes with mild venom not dangerous to humans. What snake is this?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (44, 'Common Wolf Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (45, 10, 'identify_by_description', 'A small pit viper with a distinctive upturned snout and one of the most common causes of snakebite locally. What snake is this?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (45, 'Hump-nosed Pit Viper', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (46, 11, 'identify_by_description', 'A vivid green arboreal pit viper endemic to Sri Lanka with heat-sensing pits and hemotoxic venom. What snake is this?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (46, 'Sri Lanka Green Pit Viper', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (47, 12, 'identify_by_description', 'A semi-aquatic snake found near ponds and paddy fields that feeds mainly on fish and frogs. What snake is this?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (47, 'Checkered Keelback', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (48, 13, 'identify_by_description', 'A large constrictor exceeding 4 metres found in forests near water and protected in Sri Lanka. What snake is this?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (48, 'Indian Python', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (49, 14, 'identify_by_description', 'A small burrowing snake that mimics venomous species by displaying the bright red underside of its tail. What snake is this?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (49, 'Sri Lanka Pipe Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (50, 15, 'identify_by_description', 'A fast-moving daytime snake with distinct dark body bands common in dry scrub zones. What snake is this?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (50, 'Banded Racer', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (51, 16, 'identify_by_description', 'A widespread highly venomous cobra with potent neurotoxic and cytotoxic venom. What snake is this?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (51, 'Indian Cobra', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (52, 17, 'identify_by_description', 'A reddish-brown arboreal and nocturnal pit viper from the wet zone with haemotoxic venom. What snake is this?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (52, 'Ceylon Fer-de-Lance', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (53, 18, 'identify_by_description', 'One of the largest snakes in Sri Lanka at up to 3 metres, aggressive but harmless, controlling rodent populations. What snake is this?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (53, 'Oriental Rat Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (54, 19, 'identify_by_description', 'An endemic gliding snake that flattens its body to travel between trees; rear-fanged venom harmless to humans. What snake is this?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (54, 'Sri Lanka Flying Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (55, 20, 'identify_by_description', "One of Asia's most venomous snakes, docile by day but extremely dangerous at night with neurotoxic venom. What snake is this?", 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (55, 'Common Krait', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (56, 21, 'identify_by_description', 'A secretive burrowing elapid with a bright red tail that possesses potent neurotoxic venom. What snake is this?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (56, 'Slender Coral Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (57, 22, 'identify_by_description', 'A rare arboreal pit viper found at higher elevations with green camouflage in montane vegetation. What snake is this?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (57, 'Large-scaled Pit Viper', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (58, 23, 'identify_by_description', 'A tiny blind burrowing snake mistaken for an earthworm and the only known all-female snake species. What snake is this?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (58, 'Sri Lanka Worm Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (59, 24, 'identify_by_description', 'A slender arboreal snake that flattens its neck to reveal striking blue and orange flanks as a threat display. What snake is this?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (59, 'Painted Bronzeback', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (60, 25, 'identify_by_description', 'A semi-aquatic keelback found along streams and wetlands, olive-green above with a yellowish belly. What snake is this?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (60, 'Olive Keelback', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (61, 26, 'identify_by_description', 'A rarely encountered specialist that swallows whole bird eggs and regurgitates the crushed shell. What snake is this?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (61, 'Indian Egg-Eating Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (62, 27, 'identify_by_description', 'A small secretive snake named for its curved rear teeth used to slit open reptile eggs. What snake is this?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (62, 'Sri Lanka Kukri Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (63, 28, 'identify_by_description', "The world's longest snake by length, occasionally found in Sri Lanka, with an intricate net-like pattern. What snake is this?", 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (63, 'Reticulated Python', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (64, 29, 'identify_by_description', 'A large nocturnal rear-fanged snake in forests that rarely bites humans and feeds on lizards. What snake is this?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (64, 'Forsten''s Cat Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (65, 30, 'identify_by_description', 'An endemic burrowing snake with a shielded tail tip living underground in moist hill-country soil. What snake is this?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (65, 'Sri Lanka Shieldtail', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (66, 31, 'identify_by_description', 'A small attractively patterned keelback with pale body stripes common in grasslands. What snake is this?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (66, 'Buff-striped Keelback', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (67, 32, 'identify_by_description', 'A dusky vine snake relative with horizontal pupils that hunts lizards in low vegetation. What snake is this?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (67, 'Ceylon Coachwhip', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (68, 33, 'identify_by_description', 'A slender nocturnal arboreal boa with heat-sensitive labial pits recorded in Sri Lankan forests. What snake is this?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (68, 'Sri Lanka Tree Boa', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (69, 34, 'identify_by_description', 'A slim secretive constrictor with smooth scales feeding on lizards and small rodents. What snake is this?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (69, 'Common Smooth Snake', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (70, 35, 'identify_by_description', 'An endemic arboreal pit viper often found coiled in palm and banana foliage. What snake is this?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (70, 'Sri Lanka Palm Viper', 1);

-- ── venom_level (35 questions) ──────────────────────
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (71, 1, 'venom_level', 'What is the venom level of the Common Cat Snake?', 1, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (71, 'mild', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (72, 2, 'venom_level', 'How venomous is the Ceylon Krait?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (72, 'high', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (73, 3, 'venom_level', 'What venom classification applies to the Spectacled Cobra?', 1, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (73, 'high', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (74, 4, 'venom_level', 'Is the Green Vine Snake venomous, mildly venomous, or non-venomous?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (74, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (75, 5, 'venom_level', "Select the correct venom level for the Russell's Viper.", 1, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (75, 'high', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (76, 6, 'venom_level', 'What is the venom level of the Ceylon Trinket Snake?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (76, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (77, 7, 'venom_level', 'How venomous is the Common Sand Boa?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (77, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (78, 8, 'venom_level', 'What venom classification applies to the Starred Bronzeback?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (78, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (79, 9, 'venom_level', 'Is the Common Wolf Snake venomous, mildly venomous, or non-venomous?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (79, 'mild', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (80, 10, 'venom_level', 'Select the correct venom level for the Hump-nosed Pit Viper.', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (80, 'mild', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (81, 11, 'venom_level', 'What is the venom level of the Sri Lanka Green Pit Viper?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (81, 'high', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (82, 12, 'venom_level', 'How venomous is the Checkered Keelback?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (82, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (83, 13, 'venom_level', 'What venom classification applies to the Indian Python?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (83, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (84, 14, 'venom_level', 'Is the Sri Lanka Pipe Snake venomous, mildly venomous, or non-venomous?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (84, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (85, 15, 'venom_level', 'Select the correct venom level for the Banded Racer.', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (85, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (86, 16, 'venom_level', 'What is the venom level of the Indian Cobra?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (86, 'high', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (87, 17, 'venom_level', 'How venomous is the Ceylon Fer-de-Lance?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (87, 'high', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (88, 18, 'venom_level', 'What venom classification applies to the Oriental Rat Snake?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (88, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (89, 19, 'venom_level', 'Is the Sri Lanka Flying Snake venomous, mildly venomous, or non-venomous?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (89, 'mild', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (90, 20, 'venom_level', 'Select the correct venom level for the Common Krait.', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (90, 'high', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (91, 21, 'venom_level', 'What is the venom level of the Slender Coral Snake?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (91, 'high', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (92, 22, 'venom_level', 'How venomous is the Large-scaled Pit Viper?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (92, 'high', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (93, 23, 'venom_level', 'What venom classification applies to the Sri Lanka Worm Snake?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (93, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (94, 24, 'venom_level', 'Is the Painted Bronzeback venomous, mildly venomous, or non-venomous?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (94, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (95, 25, 'venom_level', 'Select the correct venom level for the Olive Keelback.', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (95, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (96, 26, 'venom_level', 'What is the venom level of the Indian Egg-Eating Snake?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (96, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (97, 27, 'venom_level', 'How venomous is the Sri Lanka Kukri Snake?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (97, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (98, 28, 'venom_level', 'What venom classification applies to the Reticulated Python?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (98, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (99, 29, 'venom_level', "Is the Forsten's Cat Snake venomous, mildly venomous, or non-venomous?", 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (99, 'mild', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (100, 30, 'venom_level', 'Select the correct venom level for the Sri Lanka Shieldtail.', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (100, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (101, 31, 'venom_level', 'What is the venom level of the Buff-striped Keelback?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (101, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (102, 32, 'venom_level', 'How venomous is the Ceylon Coachwhip?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (102, 'mild', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (103, 33, 'venom_level', 'What venom classification applies to the Sri Lanka Tree Boa?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (103, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (104, 34, 'venom_level', 'Is the Common Smooth Snake venomous, mildly venomous, or non-venomous?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (104, 'non-venomous', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (105, 35, 'venom_level', 'Select the correct venom level for the Sri Lanka Palm Viper.', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (105, 'high', 1);

-- ── scientific_name (35 questions) ──────────────────
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (106, 1, 'scientific_name', 'What is the scientific name of the Common Cat Snake?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (106, 'Boiga trigonata', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (107, 2, 'scientific_name', 'Give the binomial name for the Ceylon Krait.', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (107, 'Bungarus ceylonicus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (108, 3, 'scientific_name', 'What is the Latin name for the Spectacled Cobra?', 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (108, 'Naja naja', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (109, 4, 'scientific_name', 'Which scientific name belongs to the Green Vine Snake?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (109, 'Ahaetulla nasuta', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (110, 5, 'scientific_name', "Identify the correct scientific name for the Russell's Viper.", 2, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (110, 'Daboia russelii', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (111, 6, 'scientific_name', 'What is the scientific name of the Ceylon Trinket Snake?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (111, 'Coelognathus helena', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (112, 7, 'scientific_name', 'Give the binomial name for the Common Sand Boa.', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (112, 'Eryx conicus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (113, 8, 'scientific_name', 'What is the Latin name for the Starred Bronzeback?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (113, 'Dendrelaphis punctulatus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (114, 9, 'scientific_name', 'Which scientific name belongs to the Common Wolf Snake?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (114, 'Lycodon aulicus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (115, 10, 'scientific_name', 'Identify the correct scientific name for the Hump-nosed Pit Viper.', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (115, 'Hypnale hypnale', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (116, 11, 'scientific_name', 'What is the scientific name of the Sri Lanka Green Pit Viper?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (116, 'Trimeresurus trigonocephalus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (117, 12, 'scientific_name', 'Give the binomial name for the Checkered Keelback.', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (117, 'Fowlea piscator', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (118, 13, 'scientific_name', 'What is the Latin name for the Indian Python?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (118, 'Python molurus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (119, 14, 'scientific_name', 'Which scientific name belongs to the Sri Lanka Pipe Snake?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (119, 'Cylindrophis maculatus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (120, 15, 'scientific_name', 'Identify the correct scientific name for the Banded Racer.', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (120, 'Argyrogena fasciolata', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (121, 16, 'scientific_name', 'What is the scientific name of the Indian Cobra?', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (121, 'Naja naja naja', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (122, 17, 'scientific_name', 'Give the binomial name for the Ceylon Fer-de-Lance.', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (122, 'Trimeresurus erythrurus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (123, 18, 'scientific_name', 'What is the Latin name for the Oriental Rat Snake?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (123, 'Ptyas mucosa', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (124, 19, 'scientific_name', 'Which scientific name belongs to the Sri Lanka Flying Snake?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (124, 'Chrysopelea taprobanica', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (125, 20, 'scientific_name', 'Identify the correct scientific name for the Common Krait.', 3, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (125, 'Bungarus caeruleus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (126, 21, 'scientific_name', 'What is the scientific name of the Slender Coral Snake?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (126, 'Calliophis melanurus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (127, 22, 'scientific_name', 'Give the binomial name for the Large-scaled Pit Viper.', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (127, 'Trimeresurus macrolepis', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (128, 23, 'scientific_name', 'What is the Latin name for the Sri Lanka Worm Snake?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (128, 'Indotyphlops braminus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (129, 24, 'scientific_name', 'Which scientific name belongs to the Painted Bronzeback?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (129, 'Dendrelaphis pictus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (130, 25, 'scientific_name', 'Identify the correct scientific name for the Olive Keelback.', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (130, 'Atretium schistosum', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (131, 26, 'scientific_name', 'What is the scientific name of the Indian Egg-Eating Snake?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (131, 'Elachistodon westermanni', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (132, 27, 'scientific_name', 'Give the binomial name for the Sri Lanka Kukri Snake.', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (132, 'Oligodon calamarius', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (133, 28, 'scientific_name', 'What is the Latin name for the Reticulated Python?', 4, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (133, 'Malayopython reticulatus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (134, 29, 'scientific_name', "Which scientific name belongs to the Forsten's Cat Snake?", 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (134, 'Boiga forsteni', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (135, 30, 'scientific_name', 'Identify the correct scientific name for the Sri Lanka Shieldtail.', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (135, 'Uropeltis melanogaster', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (136, 31, 'scientific_name', 'What is the scientific name of the Buff-striped Keelback?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (136, 'Amphiesma stolatum', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (137, 32, 'scientific_name', 'Give the binomial name for the Ceylon Coachwhip.', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (137, 'Ahaetulla pulverulenta', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (138, 33, 'scientific_name', 'What is the Latin name for the Sri Lanka Tree Boa?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (138, 'Corallus hortulanus', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (139, 34, 'scientific_name', 'Which scientific name belongs to the Common Smooth Snake?', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (139, 'Coronella austriaca', 1);
INSERT INTO Question (question_id, snake_id, question_type, question_text, difficulty, created_at) VALUES (140, 35, 'scientific_name', 'Identify the correct scientific name for the Sri Lanka Palm Viper.', 5, '2026-01-01 00:00:00');
INSERT INTO Answer (question_id, answer_text, is_correct) VALUES (140, 'Craspedocephalus trigonocephalus', 1);

-- Total questions inserted: 140